/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Design } from "./Design";
import { DesignCountArgs } from "./DesignCountArgs";
import { DesignFindManyArgs } from "./DesignFindManyArgs";
import { DesignFindUniqueArgs } from "./DesignFindUniqueArgs";
import { CreateDesignArgs } from "./CreateDesignArgs";
import { UpdateDesignArgs } from "./UpdateDesignArgs";
import { DeleteDesignArgs } from "./DeleteDesignArgs";
import { Template } from "../../template/base/Template";
import { DesignService } from "../design.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Design)
export class DesignResolverBase {
  constructor(
    protected readonly service: DesignService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Design",
    action: "read",
    possession: "any",
  })
  async _designsMeta(
    @graphql.Args() args: DesignCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Design])
  @nestAccessControl.UseRoles({
    resource: "Design",
    action: "read",
    possession: "any",
  })
  async designs(@graphql.Args() args: DesignFindManyArgs): Promise<Design[]> {
    return this.service.designs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Design, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Design",
    action: "read",
    possession: "own",
  })
  async design(
    @graphql.Args() args: DesignFindUniqueArgs
  ): Promise<Design | null> {
    const result = await this.service.design(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Design)
  @nestAccessControl.UseRoles({
    resource: "Design",
    action: "create",
    possession: "any",
  })
  async createDesign(@graphql.Args() args: CreateDesignArgs): Promise<Design> {
    return await this.service.createDesign({
      ...args,
      data: {
        ...args.data,

        template: args.data.template
          ? {
              connect: args.data.template,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Design)
  @nestAccessControl.UseRoles({
    resource: "Design",
    action: "update",
    possession: "any",
  })
  async updateDesign(
    @graphql.Args() args: UpdateDesignArgs
  ): Promise<Design | null> {
    try {
      return await this.service.updateDesign({
        ...args,
        data: {
          ...args.data,

          template: args.data.template
            ? {
                connect: args.data.template,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Design)
  @nestAccessControl.UseRoles({
    resource: "Design",
    action: "delete",
    possession: "any",
  })
  async deleteDesign(
    @graphql.Args() args: DeleteDesignArgs
  ): Promise<Design | null> {
    try {
      return await this.service.deleteDesign(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Template, {
    nullable: true,
    name: "template",
  })
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "read",
    possession: "any",
  })
  async getTemplate(
    @graphql.Parent() parent: Design
  ): Promise<Template | null> {
    const result = await this.service.getTemplate(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
